name = "Les fous"
author = "Danimor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9669e9b2f3690b410dc97bade2716bae6d8cef95738376e8e73922c9981ed644"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
