name = "Les fous"
author = "Danimor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9888d2007666d9c8451c00880da1835288f36bca41cf2a631c3cf978accacc1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
