name = "Les fous"
author = "Danimor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83067a96fe3c1466fef96d89b48c6ee37c5f7697136c052f5b796d8a58ba4faa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
